---

name: JAVA CI/CD PIPELINE

on:
    push:
      branches: [main,master]
    pull_request:
      branches: [main, master]


jobs:
    test_job:
      runs-on: self-hosted #ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v5.0.0
 
        - name: Java Installation
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: "21"
            check-latest: true
        
        - name: Maven Installation
          run: |
            sudo apt update
            sudo apt install -y maven
              
        - name: Lint Check
          run: mvn checkstyle:check > mvn_lint_check_logs.txt
        
        - name: Aqua Security Trivy
          uses: aquasecurity/trivy-action@0.33.1
          with:
            scan-type: 'fs'
            scan-ref: '.'
            output: trivy-report.json
            cache: 'false'

        - name: Test
          run: |
            mvn test || true

        - name: Build With Maven
          run: |
            mvn clean install && ls ./target
        
        - name: Upload Artifact 
          uses: actions/upload-artifact@v4.6.2
          with:
            name: targetfolder
            path: "./target/myweb-8.6.9.war"
            if-no-files-found: error
            retention-days: 2

        

        # - name: Testing
        #   run: |
        #     echo "hi my name is harshith"
        #     ls -lar
        #     pwd
        #     date
        #     uptime
        #     last -a
        #     cat /etc/passwd || true
        #     cat /proc/cpuinfo
        
            


