---

name: JAVA CI/CD PIPELINE

on:
    push:
      branches: [main,master]
    pull_request:
      branches: [main, master]


jobs:
    test_job:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Testing
          run: |
            echo "hi my name is harshith"
            ls -lar
            pwd
            date
            uptime
            last -a
            cat /etc/passwd || true
            cat proc/cpuinfo
        


